// Copyright 2022 beekeeb
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
#//include "config_common.h"

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
#define PMW33XX_CS_PIN GP13
//#define WS2812_PIO_USE_SPI1
#define SPI_DRIVER	SPID1
#define SPI_SCK_PIN	GP10
#define SPI_MISO_PIN	GP12
#define SPI_MOSI_PIN	GP11
#define USB_POLLING_INTERVAL_MS 1
#define FORCE_NKRO
#define RGBLIGHT_LED_COUNT 25
#define RGBLIGHT_LIMIT_VAL 64
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
