// Copyright 2022 beekeeb
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

//#include "config_common.h"

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#ifdef RGB_MATRIX_ENABLE
#define WS2812_DI_PIN GP28
#define DRIVER_LED_TOTAL 120
#define RGB_MATRIX_LED_COUNT 120
#define RGBLED_NUM 120
#define WS2812_PIO_USE_PIO1
//#define RGBLED_SPLIT { 120, 0 }

     /* Enable Framebuffer and keypress effects */
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define ENABLE_RGB_MATRIX_BREATHING
/*#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 80*/

#endif
//#define NOP_FUDGE 0.4
//#define RGBLIGHT_LIMIT_VAL 96

#define WS2812_PIO_USE_PIO1

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define TAPPING_TOGGLE 3

#define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY
#define COMBO_TERM 65
#define COMBO_VARIABLE_LEN
//#define COMBO_COUNT 0


#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 6
#define MOUSEKEY_TIME_TO_MAX 64
#define MEDIA_KEY_DELAY 2


//#define USB_POLLING_INTERVAL_MS 1
//#define RGBW
//#define RGBLIGHT_LAYERS
//#define RGBLIGHT_SPLIT
//#define RGBLIGHT_LAYER_BLINK
//#define RGBLIGHT_SLEEP  // allows us to use rgblight_suspend() and rgblight_wakeup() in keymap.c
//#define RGBLIGHT_TIMEOUT 60000  // 30 seconds
//#define RGB_MATRIX_SLEEP
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
//#define POINTING_DEVICE_ROTATION_180
#define MASTER_RIGHT
//#define POINTING_DEVICE_TASK_THROTTLE_MS 10
//#define CIRQUE_PINNACLE_DIAMETER_MM 40
#define AZOTEQ_IQS5XX_TPS65
#define AZOTEQ_IQS5XX_TAP_ENABLE TRUE
#define AZOTEQ_IQS5XX_TWO_FINGER_TAP_ENABLE TRUE
#define AZOTEQ_IQS5XX_PRESS_AND_HOLD_ENABLE TRUE
//#define AZOTEQ_IQS5XX_SWIPE_X_ENABLE TRUE
//#define AZOTEQ_IQS5XX_SWIPE_Y_ENABLE TRUE
//#define AZOTEQ_IQS5XX_ZOOM_ENABLE TRUE
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 2
#define AUTO_MOUSE_TIME 2500
//#define AZOTEQ_IQS5XX_ROTATION_90
#define I2C1_SDA_PIN GP26
#define I2C1_SCL_PIN GP27
//#define RGBLIGHT_LAYERS
//#define RGBLIGHT_MAX_LAYERS 5
//#define ENABLE_RGB_MATRIX_STARLIGHT
//#define RGBLIGHT_EFFECT_BREATHING
//#define RGBLIGHT_EFFECT_RAINBOW_MOOD
//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
//#define RGBLIGHT_EFFECT_SNAKE
//#define RGBLIGHT_EFFECT_KNIGHT
///#define RGBLIGHT_EFFECT_CHRISTMAS
//#define RGBLIGHT_EFFECT_STATIC_GRADIENT
//#define RGBLIGHT_EFFECT_RGB_TEST
//#define RGBLIGHT_EFFECT_ALTERNATING

#define LEADER_TIMEOUT 750

//#define RGBLIGHT_EFFECT_TWINKLE
//#define RGBLIGHT_EFFECT_TWINKLE_LIFE 50
//#define RGBLIGHT_EFFECT_TWINKLE_PROBABILITY 1 / 1000
//#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_TWINKLE+2

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE

#define COMBO_MUST_PRESS_IN_ORDER_PER_COMBO
