// Copyright 2022 beekeeb
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

//#include "config_common.h"

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#ifdef RGB_MATRIX_ENABLE
#define WS2812_DI_PIN GP28
#define DRIVER_LED_TOTAL 12
#define RGB_MATRIX_LED_COUNT 12
#define RGBLED_NUM 12
#define WS2812_PIO_USE_PIO1
#define RGBLED_SPLIT { 12, 0 }

     /* Enable Framebuffer and keypress effects */
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define ENABLE_RGB_MATRIX_BREATHING
/*#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 80*/

#endif
//#define NOP_FUDGE 0.4
#define RGBLIGHT_LIMIT_VAL 96

#define WS2812_PIO_USE_PIO1
#define TAPPING_TERM 220
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define COMBO_TERM 65

//#define COMBO_COUNT 0
#define MOUSEKEY_DELAY 50
#define MOUSEKEY_INTERVAL 16
#define MEDIA_KEY_DELAY 2
#define TAPPING_TOGGLE 2

//#define USB_POLLING_INTERVAL_MS 1
#define RGBW
#define RGB_LIGHT_TIMEOUT 60000
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
//#define POINTING_DEVICE_ROTATION_180
#define MASTER_RIGHT
#define POINTING_DEVICE_TASK_THROTTLE_MS 10
#define CIRQUE_PINNACLE_DIAMETER_MM 40
#define CIRQUE_PINNACLE_CURVED_OVERLAY
#define CIRQUE_PINNACLE_TAP_ENABLE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE // Circular scroll.;::
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#define PIANTOR42_DRAGSCROLL_REVERSE_X
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 2

#define I2C1_SDA_PIN GP26
#define I2C1_SCL_PIN GP27

#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 32

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE

