// Copyright 2022 beekeeb
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
#//include "config_common.h"

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

//#define SERIAL_USART_FULL_DUPLEX
//#define SERIAL_USART_TX_PIN GP0
//#define SERIAL_USART_RX_PIN GP1

#ifdef RGB_MATRIX_ENABLE
#define WS2812_DI_PIN GP16
#define DRIVER_LED_TOTAL 25
#define RGB_MATRIX_LED_COUNT25
#define RGBLED_NUM 25
#define WS2812_PIO_USE_PIO1

     /* Enable Framebuffer and keypress effects */
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define ENABLE_RGB_MATRIX_BREATHING
#endif

/*#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 80*/

#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 32

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE

#define RGBLIGHT_LIMIT_VAL 32

#define WS2812_PIO_USE_PIO1
#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_RGB

#define MOUSEKEY_DELAY 50
#define MOUSEKEY_INTERVAL 16
#define MEDIA_KEY_DELAY 2

#define USB_POLLING_INTERVAL_MS 1
#define FORCE_NKRO

# define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL
